# Generated by Django 4.0.5 on 2022-08-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Item',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(max_length=2, null=True),
        ),
    ]
