# Generated by Django 4.0.5 on 2022-08-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_review_item_review_name_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
